-- Núcleo agronómico de enfermedades de soja v2.0.
-- Fuente primaria: patogenos_soja_condiciones_ambientales 14-08.xlsx (Natali).
-- La migración conserva el historial y retira la regla foliar genérica para evitar doble señal.

create table if not exists catalogo_enfermedades (
  id uuid primary key default gen_random_uuid(),
  cultivo text not null,
  clave text not null,
  categoria text not null,
  nombre text not null,
  nombre_cientifico text,
  organo_afectado text not null,
  evaluabilidad text not null check (evaluabilidad in ('EVALUABLE','PARCIALMENTE_EVALUABLE','NO_EVALUABLE','PENDIENTE_EVIDENCIA')),
  modo_avizor text check (modo_avizor in ('ESTABLE','EXPERIMENTAL')),
  estado_catalogo text not null check (estado_catalogo in ('activa','catalogada','retirada')),
  condiciones_normalizadas jsonb not null,
  factores_no_observables text[] not null default '{}',
  cobertura_esperada text not null check (cobertura_esperada in ('COMPLETA','PARCIAL','INSUFICIENTE')),
  fuentes jsonb not null,
  version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (cultivo, clave, version),
  check (jsonb_typeof(condiciones_normalizadas) = 'object'),
  check (jsonb_typeof(fuentes) = 'array')
);

-- El índice legacy impedía varias reglas específicas dentro de una misma categoría.
-- La identidad v2 sigue protegida por reglas_agronomicas_clave_version_idx.
drop index if exists reglas_agronomicas_unique_rule_idx;

insert into catalogo_enfermedades
  (cultivo,clave,categoria,nombre,nombre_cientifico,organo_afectado,evaluabilidad,estado_catalogo,condiciones_normalizadas,factores_no_observables,cobertura_esperada,fuentes,version)
values
('soja','antracnosis','fin_ciclo','Antracnosis','Colletotrichum truncatum / C. gloeosporioides','vainas, tallos y pecíolos','PARCIALMENTE_EVALUABLE','activa','{"temperatura_aire":[25,30],"hr_min":85,"mojado_horas":12,"fenologia":"V0-R7; prioridad R3-R4","ventana_dias":5}'::jsonb,array['mojado_foliar_observado','rastrojo','inoculo'],'PARCIAL',jsonb_build_array(jsonb_build_object('institucion','Natali','referencia','patogenos_soja_condiciones_ambientales 14-08.xlsx'),jsonb_build_object('institucion','INTA','url','https://repositorio.inta.gob.ar/xmlui/bitstream/handle/20.500.12123/15954/INTA_CRBsAsNorte_EEAPergamino_Ivancovich_A_Enfermedades_soja_diagnotico_tratamiento.pdf?isAllowed=y&sequence=1','consultado','2026-08-24')),'2.0'),
('soja','sindrome_muerte_subita','raiz','Síndrome de muerte súbita','Fusarium tucumaniae / F. virguliforme','raíz','NO_EVALUABLE','catalogada','{"temperatura":"templada/fresca inicial","hr_min":85,"humedad_suelo":"saturada","fenologia":"V0-R7"}'::jsonb,array['saturacion_calibrada','compactacion','drenaje','nematodos','inoculo'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"University of Minnesota Extension","url":"https://extension.umn.edu/soybean-pest-management/sudden-death-syndrome-soybean","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','phytophthora_sojae','raiz','Podredumbre del tallo y de la raíz','Phytophthora sojae','raíz y tallo','NO_EVALUABLE','catalogada','{"temperatura_aire":[25,30],"humedad_suelo":"saturada/inundada","fenologia":"V0-R7"}'::jsonb,array['saturacion_calibrada','inundacion_observada','drenaje','inoculo'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"INTA","url":"https://intainforma.inta.gob.ar/como-prevenir-el-desarrollo-de-plagas-y-enfermedades/","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','pythium','plantula','Damping-off','Pythium spp.','semilla y plántula','NO_EVALUABLE','catalogada','{"temperatura_aire":[10,36],"humedad_suelo":"anegada","fenologia":"V0-R7"}'::jsonb,array['anegamiento_observado','saturacion_calibrada','inoculo'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"INTA","url":"https://intainforma.inta.gob.ar/como-prevenir-el-desarrollo-de-plagas-y-enfermedades/","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','fusarium_raiz','raiz','Fusarium','Fusarium spp.','raíz','NO_EVALUABLE','catalogada','{"temperatura_aire":[20,25],"hr_min":85,"humedad_suelo":"húmeda/saturada","fenologia":"V0-R7"}'::jsonb,array['saturacion_calibrada','drenaje','estres_planta','inoculo'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"Crop Protection Network","url":"https://cropprotectionnetwork.org/publications/an-overview-of-soybean-seedling-diseases","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','mancha_marron','foliar','Mancha marrón','Septoria glycines','hojas','PARCIALMENTE_EVALUABLE','catalogada','{"temperatura_aire":[25,30],"optimo":28,"mojado_horas":[6,36],"lluvia":"frecuente","fenologia":"V1-R7","ventana_dias":5}'::jsonb,array['mojado_foliar_observado','rastrojo','inoculo'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"University of Minnesota Extension","url":"https://extension.umn.edu/agriculture/crop-production/soybean/septoria-brown-spot","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','cercospora_kikuchii','fin_ciclo','Tizón de la hoja y mancha púrpura','Cercospora kikuchii','hojas y semilla','PARCIALMENTE_EVALUABLE','activa','{"temperatura_aire":[23,28],"hr_min":85,"hr_persistente":true,"fenologia":"V1-R7","ventana_dias":5}'::jsonb,array['rastrojo','semilla_infectada','inoculo'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"INTA","url":"https://repositorio.inta.gob.ar/bitstream/handle/20.500.12123/3276/Agro_barrow_55_p.6-7.pdf?isAllowed=y&sequence=1","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','complejo_fin_ciclo','fin_ciclo','Complejo de hongos de fin de ciclo','Cercospora spp., Septoria spp., Colletotrichum spp.','hojas, tallos y vainas','NO_EVALUABLE','catalogada','{"temperatura_aire":[20,30],"hr_min":85,"lluvia":"constante","fenologia":"R3-R6"}'::jsonb,array['mojado_foliar_observado','inoculo'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"INTA","url":"https://intainforma.inta.gob.ar/como-prevenir-el-desarrollo-de-plagas-y-enfermedades/","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','roya_asiatica','foliar','Roya asiática de la soja','Phakopsora pachyrhizi','hojas','PARCIALMENTE_EVALUABLE','activa','{"temperatura_aire":[14,28],"hr_favorable_min":75,"hr_fuertemente_favorable_min":80,"mojado_horas_min":6,"lluvia":true,"ventana_dias":5}'::jsonb,array['mojado_foliar_observado','hospedante_alternativo','inoculo'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"SINAVIMO/SENASA","url":"https://www.sinavimo.gob.ar/plaga/phakopsora-pachyrhizi","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','sclerotinia','tallo','Podredumbre húmeda del tallo','Sclerotinia sclerotiorum','tallo','PARCIALMENTE_EVALUABLE','activa','{"temperatura_aire":[10,28],"hr_min":85,"mojado_horas":[42,72],"fenologia":"R2-R3","ventana_dias":5}'::jsonb,array['mojado_foliar_observado','canopeo','drenaje','esclerocios','fenologia_aplicada'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"SINAVIMO/SENASA","url":"https://www.sinavimo.gob.ar/plaga/sclerotinia-sclerotiorum","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','podredumbre_marron_tallo','tallo','Podredumbre marrón del tallo','Cadophora gregata','tallo','NO_EVALUABLE','catalogada','{"temperatura_aire":[17,27],"humedad_suelo":"alta","fenologia":"R1-R7"}'::jsonb,array['humedad_suelo_calibrada','inoculo'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"}]'::jsonb,'2.0'),
('soja','macrophomina','raiz_tallo','Podredumbre carbonosa de raíz y tallo','Macrophomina phaseolina','raíz y tallo','PARCIALMENTE_EVALUABLE','activa','{"temperatura_aire_min":30,"hr_aprox":40,"estres_hidrico":true,"fenologia":"VC-R6","ventana_dias":14}'::jsonb,array['inoculo','fenologia_aplicada'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"Crop Protection Network","url":"https://cropprotectionnetwork.org/publications/an-overview-of-charcoal-rot-of-soybean","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','sclerotium_rolfsii','raiz','Tizón por Sclerotium','Sclerotium rolfsii','raíz y cuello','NO_EVALUABLE','catalogada','{"temperatura_aire":[30,35],"hr_min":85,"humedad":"alta"}'::jsonb,array['tipo_suelo','humedad_suelo_calibrada','inoculo'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"}]'::jsonb,'2.0'),
('soja','rhizoctonia','raiz','Podredumbre de la raíz por Rhizoctonia','Rhizoctonia solani','raíz y plántula','PENDIENTE_EVIDENCIA','catalogada','{"temperatura_suelo":[26,32],"humedad_suelo":"seca","fenologia":"VC"}'::jsonb,array['sequedad_suelo_calibrada','inoculo'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"Crop Protection Network","url":"https://cropprotectionnetwork.org/publications/an-overview-of-soybean-seedling-diseases","consultado":"2026-08-24","nota":"La fuente indica suelo cálido y húmedo, no seco; conflicto real."}]'::jsonb,'2.0'),
('soja','cancro_meridional','tallo','Cancro del tallo meridional','Diaporthe phaseolorum var. meridionalis','tallo','NO_EVALUABLE','catalogada','{"temperatura_aire":[25,30],"lluvia":true,"viento":true,"fenologia":"R1-R7","latencia_dias":[15,20]}'::jsonb,array['infeccion_temprana','inoculo','latencia_no_es_ventana_climatica'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"}]'::jsonb,'2.0'),
('soja','cancro_caulivora','tallo','Cancro del tallo del norte','Diaporthe phaseolorum var. caulivora','tallo','PARCIALMENTE_EVALUABLE','catalogada','{"temperatura_aire":[20,25],"humedad":"alta","lluvia":"frecuente","fenologia":"R1-R7","ventana_dias":7}'::jsonb,array['infeccion_temprana','rastrojo','inoculo','fenologia_aplicada'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"}]'::jsonb,'2.0'),
('soja','mancha_ojo_rana','foliar','Mancha ojo de rana','Cercospora sojina','hojas','PARCIALMENTE_EVALUABLE','activa','{"temperatura_aire":[25,35],"hr_min_exclusivo":90,"lluvia":"abundante","rocio":true,"fenologia":"V1-R7","ventana_dias":5}'::jsonb,array['rocio_observado','inoculo','fenologia_aplicada'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"},{"institucion":"University of Minnesota Extension","url":"https://extension.umn.edu/agriculture/crop-production/soybean/frogeye-leaf-spot","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','tizon_bacteriano','bacteriosis','Tizón bacteriano','Pseudomonas syringae pv. glycinea','hojas','PARCIALMENTE_EVALUABLE','activa','{"temperatura_aire":[15,20],"tormenta_lluvia":true,"viento":true,"ventana_dias":3}'::jsonb,array['granizo','lesiones','inoculo'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx; Definiciones: fresca=15-20 C"},{"institucion":"University of Minnesota Extension","url":"https://extension.umn.edu/pest-management/bacterial-blight-soybean","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','pustula_bacteriana','bacteriosis','Pústula bacteriana','Xanthomonas axonopodis pv. glycines','hojas','PARCIALMENTE_EVALUABLE','activa','{"temperatura_aire":[25,30],"tormenta_lluvia":true,"viento":true,"ventana_dias":3}'::jsonb,array['granizo','lesiones','inoculo'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx; Definiciones: cálida=25-30 C"},{"institucion":"University of Minnesota Extension","url":"https://extension.umn.edu/agriculture/crop-production/soybean/bacterial-pustule-soybean","consultado":"2026-08-24"}]'::jsonb,'2.0'),
('soja','smv','virus','Virus del mosaico común de la soja','Soybean mosaic virus','sistémico','NO_EVALUABLE','catalogada','{"vector":"afidos","viento":true}'::jsonb,array['presencia_vectores','actividad_vectores','inoculo'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"}]'::jsonb,'2.0'),
('soja','amv','virus','Virus del mosaico de la alfalfa','Alfalfa mosaic virus','sistémico','NO_EVALUABLE','catalogada','{"vector":"afidos","viento":true}'::jsonb,array['presencia_vectores','actividad_vectores','inoculo'],'INSUFICIENTE','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx"}]'::jsonb,'2.0'),
('soja','oidio','foliar','Oídio','Erysiphe diffusa','hojas','PARCIALMENTE_EVALUABLE','activa','{"temperatura_aire":[18,24],"hr_definicion_min_exclusivo":90,"se_detiene_aprox":30,"ventana_dias":5}'::jsonb,array['susceptibilidad_cultivar','inoculo','fenologia_aplicada'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx; Definiciones: HR alta >90%"},{"institucion":"University of Minnesota Extension","url":"https://extension.umn.edu/agriculture/crop-production/soybean/powdery-mildew-soybean","consultado":"2026-08-24","nota":"Respalda tiempo fresco; no respalda usar lluvia como requisito."}]'::jsonb,'2.0'),
('soja','mildiu','foliar','Mildiu','Peronospora manshurica','hojas y semilla','PARCIALMENTE_EVALUABLE','activa','{"temperatura_aire":[20,22],"hr_definicion_min_exclusivo":90,"fenologia":"R1-R7","ventana_dias":5}'::jsonb,array['rocio_observado','inoculo','fenologia_aplicada'],'PARCIAL','[{"institucion":"Natali","referencia":"patogenos_soja_condiciones_ambientales 14-08.xlsx; Definiciones: HR alta >90%"},{"institucion":"University of Minnesota Extension","url":"https://extension.umn.edu/agriculture/crop-production/soybean/downy-mildew","consultado":"2026-08-24"}]'::jsonb,'2.0')
on conflict (cultivo,clave,version) do update set
  evaluabilidad=excluded.evaluabilidad, estado_catalogo=excluded.estado_catalogo,
  condiciones_normalizadas=excluded.condiciones_normalizadas, factores_no_observables=excluded.factores_no_observables,
  cobertura_esperada=excluded.cobertura_esperada, fuentes=excluded.fuentes, updated_at=now();

update catalogo_enfermedades set modo_avizor = case
  when clave in ('cercospora_kikuchii','roya_asiatica','macrophomina','oidio','mildiu') then 'ESTABLE'
  when clave in ('antracnosis','sclerotinia','mancha_ojo_rana','tizon_bacteriano','pustula_bacteriana') then 'EXPERIMENTAL'
  else null
end
where cultivo='soja' and version='2.0';

-- Evita evaluar simultáneamente la señal genérica anterior y las específicas y deja auditoría.
with anteriores as (
  select id, to_jsonb(reglas_agronomicas.*) as valor_anterior
  from reglas_agronomicas where cultivo='soja' and clave='enfermedades_foliares' and estado <> 'retirada'
), retiradas as (
  update reglas_agronomicas r set estado='retirada', activa=false, updated_at=now()
  from anteriores a where r.id=a.id returning r.id, a.valor_anterior, to_jsonb(r.*) as valor_nuevo
)
insert into auditoria(actor_id,actor_tipo,accion,entidad,entidad_id,valor_anterior,valor_nuevo,request_id)
select 'migration-009','service','retirar_version','regla',id::text,valor_anterior,valor_nuevo,gen_random_uuid() from retiradas;

with nuevas(clave,categoria,ventana,fuente,limitaciones,definicion) as (values
('antracnosis','fin_ciclo',5,'Natali 14-08; INTA','Evaluación parcial: sin mojado foliar observado, rastrojo ni inóculo.','{"niveles":[{"orden":1,"clave":"condiciones_detectadas","orden_visual":1,"etiqueta":"Ambiente compatible con antracnosis","explicacion":"Coinciden temperatura y humedad; no constituye diagnóstico.","recomendacion":"Monitorear vainas, tallos y pecíolos.","condiciones":[{"variable":"temperatura_media","agregador":"media_ventana","operador":"between","valor":[25,30],"unidad":"C"},{"variable":"humedad_relativa","agregador":"media_ventana","operador":"gte","valor":85,"unidad":"%"}]}],"sin_coincidencia":{"estado":"sin_condiciones"}}'),
('cercospora_kikuchii','fin_ciclo',5,'Natali 14-08; INTA','Evaluación parcial: no observa rastrojo, semilla infectada ni inóculo.','{"niveles":[{"orden":1,"clave":"condiciones_detectadas","orden_visual":1,"etiqueta":"Ambiente compatible con tizón por Cercospora","explicacion":"Coinciden temperatura y humedad persistente; no constituye diagnóstico.","recomendacion":"Monitorear el lote, especialmente en etapas reproductivas.","condiciones":[{"variable":"temperatura_media","agregador":"media_ventana","operador":"between","valor":[23,28],"unidad":"C"},{"variable":"humedad_relativa","agregador":"dias_con_condicion","operador":"gte","valor":4,"unidad":"dias","subcondicion":{"operador":"gte","valor":85,"unidad":"%"}}]}],"sin_coincidencia":{"estado":"sin_condiciones"}}'),
('roya_asiatica','foliar',5,'Natali 14-08; SINAVIMO/SENASA','Evaluación parcial: no mide 6 h de mojado/rocío ni presencia de inóculo. HR >75% es el umbral favorable primario.','{"niveles":[{"orden":1,"clave":"condiciones_detectadas","orden_visual":1,"etiqueta":"Ambiente compatible con roya asiática","explicacion":"Coinciden temperatura, humedad y precipitación reciente; no constituye diagnóstico.","recomendacion":"Intensificar el monitoreo del lote.","condiciones":[{"variable":"temperatura_media","agregador":"media_ventana","operador":"between","valor":[14,28],"unidad":"C"},{"variable":"humedad_relativa","agregador":"media_ventana","operador":"gt","valor":75,"unidad":"%"},{"variable":"precipitacion","agregador":"dias_con_condicion","operador":"gte","valor":1,"unidad":"dias","subcondicion":{"operador":"gte","valor":1,"unidad":"mm"}}]}],"sin_coincidencia":{"estado":"sin_condiciones"}}'),
('sclerotinia','tallo',5,'Natali 14-08; SINAVIMO/SENASA','Evaluación parcial: no mide 42-72 h de mojado, canopeo, drenaje, esclerocios ni aplica aún R2-R3.','{"niveles":[{"orden":1,"clave":"condiciones_detectadas","orden_visual":1,"etiqueta":"Ambiente compatible con Sclerotinia","explicacion":"Coinciden temperatura, humedad persistente y lluvia; no constituye diagnóstico.","recomendacion":"Monitorear el lote, priorizando floración y canopeos densos.","condiciones":[{"variable":"temperatura_media","agregador":"media_ventana","operador":"between","valor":[10,28],"unidad":"C"},{"variable":"humedad_relativa","agregador":"dias_con_condicion","operador":"gte","valor":3,"unidad":"dias","subcondicion":{"operador":"gte","valor":85,"unidad":"%"}},{"variable":"precipitacion","agregador":"dias_con_condicion","operador":"gte","valor":1,"unidad":"dias","subcondicion":{"operador":"gte","valor":1,"unidad":"mm"}}]}],"sin_coincidencia":{"estado":"sin_condiciones"}}'),
('macrophomina','raiz_tallo',14,'Natali 14-08; Crop Protection Network','Evaluación parcial: usa calor, HR baja y precipitación baja; no confirma estrés del cultivo ni inóculo.','{"niveles":[{"orden":1,"clave":"condiciones_detectadas","orden_visual":1,"etiqueta":"Ambiente compatible con podredumbre carbonosa","explicacion":"Coinciden calor y ambiente seco prolongado; no constituye diagnóstico.","recomendacion":"Revisar disponibilidad de agua y monitorear sectores más secos.","condiciones":[{"variable":"temperatura_max","agregador":"dias_con_condicion","operador":"gte","valor":5,"unidad":"dias","subcondicion":{"operador":"gt","valor":30,"unidad":"C"}},{"variable":"humedad_relativa","agregador":"media_ventana","operador":"lte","valor":45,"unidad":"%"},{"variable":"precipitacion","agregador":"suma_ventana","operador":"lt","valor":10,"unidad":"mm"}]}],"sin_coincidencia":{"estado":"sin_condiciones"}}'),
('mancha_ojo_rana','foliar',5,'Natali 14-08; University of Minnesota Extension','Evaluación parcial: no observa rocío, lluvia abundante formalizada, inóculo ni aplica aún fenología.','{"niveles":[{"orden":1,"clave":"condiciones_detectadas","orden_visual":1,"etiqueta":"Ambiente compatible con mancha ojo de rana","explicacion":"Coinciden temperatura y HR mayor a 90%; no constituye diagnóstico.","recomendacion":"Monitorear hojas, especialmente desde floración.","condiciones":[{"variable":"temperatura_media","agregador":"media_ventana","operador":"between","valor":[25,35],"unidad":"C"},{"variable":"humedad_relativa","agregador":"media_ventana","operador":"gt","valor":90,"unidad":"%"}]}],"sin_coincidencia":{"estado":"sin_condiciones"}}'),
('tizon_bacteriano','bacteriosis',3,'Natali 14-08; University of Minnesota Extension','Experimental. No observa tormenta, granizo, lesiones ni inóculo. El viento se conserva en la serie como dato complementario, pero no condiciona la coincidencia.','{"niveles":[{"orden":1,"clave":"condiciones_detectadas","orden_visual":1,"etiqueta":"Coincidencia experimental con ambiente de tizón bacteriano","explicacion":"Coinciden tiempo fresco y precipitación; no prueba tormenta, heridas ni enfermedad.","recomendacion":"Resultado interno para QA; no presentar como alerta pública estándar.","condiciones":[{"variable":"temperatura_media","agregador":"media_ventana","operador":"between","valor":[15,20],"unidad":"C"},{"variable":"precipitacion","agregador":"suma_ventana","operador":"gt","valor":0,"unidad":"mm"}]}],"sin_coincidencia":{"estado":"sin_condiciones"}}'),
('pustula_bacteriana','bacteriosis',3,'Natali 14-08; University of Minnesota Extension','Experimental. No observa tormenta, granizo, lesiones ni inóculo. El viento se conserva en la serie como dato complementario, pero no condiciona la coincidencia.','{"niveles":[{"orden":1,"clave":"condiciones_detectadas","orden_visual":1,"etiqueta":"Coincidencia experimental con ambiente de pústula bacteriana","explicacion":"Coinciden tiempo cálido y precipitación; no prueba tormenta, heridas ni enfermedad.","recomendacion":"Resultado interno para QA; no presentar como alerta pública estándar.","condiciones":[{"variable":"temperatura_media","agregador":"media_ventana","operador":"between","valor":[25,30],"unidad":"C"},{"variable":"precipitacion","agregador":"suma_ventana","operador":"gt","valor":0,"unidad":"mm"}]}],"sin_coincidencia":{"estado":"sin_condiciones"}}'),
('oidio','foliar',5,'Natali 14-08; University of Minnesota Extension','Evaluación parcial: HR >90% proviene de la definición primaria; la fuente externa respalda tiempo fresco, no lluvia.','{"niveles":[{"orden":1,"clave":"condiciones_detectadas","orden_visual":1,"etiqueta":"Ambiente compatible con oídio","explicacion":"Coinciden temperatura fresca y HR alta según la definición de Natali; no constituye diagnóstico.","recomendacion":"Monitorear hojas en etapas reproductivas.","condiciones":[{"variable":"temperatura_media","agregador":"media_ventana","operador":"between","valor":[18,24],"unidad":"C"},{"variable":"humedad_relativa","agregador":"media_ventana","operador":"gt","valor":90,"unidad":"%"}]}],"sin_coincidencia":{"estado":"sin_condiciones"}}'),
('mildiu','foliar',5,'Natali 14-08; University of Minnesota Extension','Evaluación parcial: no observa rocío/inóculo ni aplica aún R1-R7.','{"niveles":[{"orden":1,"clave":"condiciones_detectadas","orden_visual":1,"etiqueta":"Ambiente compatible con mildiu","explicacion":"Coinciden temperatura moderada y HR alta; no constituye diagnóstico.","recomendacion":"Monitorear hojas jóvenes, especialmente desde floración.","condiciones":[{"variable":"temperatura_media","agregador":"media_ventana","operador":"between","valor":[20,22],"unidad":"C"},{"variable":"humedad_relativa","agregador":"media_ventana","operador":"gt","valor":90,"unidad":"%"}]}],"sin_coincidencia":{"estado":"sin_condiciones"}}')
)
insert into reglas_agronomicas
  (cultivo,categoria_nombre,condicion,causas,recomendacion,regla_version,estado_regla,prioridad,activa,combinador,condiciones,clave,version,estado,ventana_dias,fuente_tecnica,limitaciones_declaradas,validado_por,validado_en,condiciones_revision,decisiones_pendientes,definicion)
select 'soja',categoria,'favorable','{}','Monitorear el lote; esta señal ambiental no constituye diagnóstico.','2.0','experimental',400,true,'all','[]',clave,'2.0',
  case when clave in ('antracnosis','sclerotinia','mancha_ojo_rana','tizon_bacteriano','pustula_bacteriana') then 'experimental' else 'vigente' end,
  ventana,fuente,limitaciones,'Fuente agronómica: Natali; normalización técnica parcial: Avizor',null,
  'Revisar al incorporar mojado foliar, fenología operativa o nueva evidencia.',array['Implementación PARCIALMENTE_EVALUABLE; no afirmar validación integral','Aplicar fenología como priorización cuando el contrato lo permita'],definicion::jsonb
from nuevas
on conflict (cultivo,clave,version) where clave is not null do update set
  categoria_nombre=excluded.categoria_nombre, estado_regla=excluded.estado_regla, estado=excluded.estado, activa=true, ventana_dias=excluded.ventana_dias,
  fuente_tecnica=excluded.fuente_tecnica, limitaciones_declaradas=excluded.limitaciones_declaradas,
  validado_por=excluded.validado_por, validado_en=excluded.validado_en, condiciones_revision=excluded.condiciones_revision,
  decisiones_pendientes=excluded.decisiones_pendientes, definicion=excluded.definicion, updated_at=now();

insert into auditoria(actor_id,actor_tipo,accion,entidad,entidad_id,valor_anterior,valor_nuevo,request_id)
select 'migration-009','service','crear_version','regla',id::text,null,
  jsonb_build_object('clave',clave,'version',version,'estado',estado,'fuente_tecnica',fuente_tecnica),gen_random_uuid()
from reglas_agronomicas where cultivo='soja' and version='2.0' and clave in
  ('antracnosis','cercospora_kikuchii','roya_asiatica','sclerotinia','macrophomina','mancha_ojo_rana','tizon_bacteriano','pustula_bacteriana','oidio','mildiu')
and not exists (
  select 1 from auditoria a where a.actor_id='migration-009' and a.accion='crear_version' and a.entidad_id=reglas_agronomicas.id::text
);
