import { Bell, CloudSun, Database, FileCheck, LockKeyhole, Mail, RefreshCcw, Share2, ShieldCheck, UserRoundCheck } from "lucide-react";
import Accordion from "@/components/Accordion";
import { PRIVACY_POLICY_LAST_UPDATED } from "@/lib/privacy/policy";
const sections=[
 {Icon:Database,title:"1. Qué datos utilizamos",text:["Para realizar una consulta, Avizor puede utilizar la localidad y provincia seleccionadas, las coordenadas asociadas, el cultivo y la información climática necesaria para generar el análisis.","También podés informar de manera opcional fecha de siembra, grupo de madurez y cultivar para mejorar la precisión del resultado.","Avizor procesa además los indicadores, señales, resultados, cobertura y demás información generada durante la consulta.","No es necesario crear una cuenta para utilizar la versión pública de Avizor."]},
 {Icon:FileCheck,title:"2. Qué no solicitamos",text:["Avizor no necesita documentos, información financiera ni datos personales que no sean necesarios para prestar el servicio.","La versión pública tampoco solicita acceso a la ubicación GPS del dispositivo.","Los datos opcionales relacionados con el cultivo se utilizan únicamente para mejorar el análisis agronómico."]},
 {Icon:Database,title:"3. Para qué utilizamos la información",text:["Utilizamos la información para generar los resultados solicitados, evaluar las condiciones agroclimáticas, mejorar la calidad y precisión de Avizor, analizar el funcionamiento de las señales y obtener estadísticas sobre el uso y comportamiento de la plataforma.","También utilizamos información técnica limitada para mantener la seguridad y el correcto funcionamiento del servicio."]},
 {Icon:RefreshCcw,title:"4. Cuánto tiempo conservamos la información",text:["Las consultas y sus resultados completos pueden conservarse durante un máximo de 18 meses.","Una vez cumplido ese período, eliminamos la información que permita asociar o reconstruir la consulta original.","Podemos conservar de manera indefinida información efectivamente anonimizada o agregada para estadísticas, análisis agronómico, comparación entre campañas y mejora de Avizor.","Los comentarios y observaciones pueden conservarse asociados durante un máximo de 24 meses."]},
 {Icon:Share2,title:"5. Compartir un resultado",text:["Avizor puede generar enlaces para compartir resultados.","Los enlaces públicos tienen una vigencia máxima de 30 días. Una vez vencidos, el resultado deja de estar disponible mediante ese enlace y será necesario realizar una nueva consulta para obtener información actualizada.","Cuando compartís mediante WhatsApp o correo electrónico, Avizor no necesita almacenar los datos del destinatario."]},
 {Icon:Bell,title:"6. Novedades de Avizor",text:["Podés elegir voluntariamente recibir novedades de Avizor proporcionando tu correo electrónico.","Esta opción es independiente de las consultas y nunca debe estar seleccionada de manera predeterminada.","Podés dejar de recibir comunicaciones en cualquier momento."]},
 {Icon:CloudSun,title:"7. Información meteorológica",text:["Avizor utiliza servicios de Open-Meteo para obtener información meteorológica y geográfica necesaria para realizar los análisis.","Solo se envía la información necesaria para realizar esas consultas, como coordenadas, período, parámetros meteorológicos o localidad cuando sea necesario."]},
 {Icon:LockKeyhole,title:"8. Cómo protegemos la información",text:["Aplicamos medidas técnicas y organizativas destinadas a limitar el acceso, proteger la información almacenada y reducir la exposición innecesaria de datos.","Avizor utiliza únicamente la información necesaria para prestar y mejorar el servicio."]},
 {Icon:UserRoundCheck,title:"9. Tus derechos",text:["Podés solicitar acceso, corrección o eliminación de la información asociada a una consulta, así como retirar un consentimiento otorgado.","Cuando la consulta haya sido realizada de manera anónima, podremos pedirte el enlace compartido u otro identificador disponible que permita localizarla razonablemente.","No solicitaremos información personal innecesaria para realizar esta gestión."]},
 {Icon:Mail,title:"10. Contacto",text:["Para consultas de privacidad, solicitudes relacionadas con tus datos o para dejar de recibir novedades, escribinos a:","letsar.software@gmail.com"]},
 {Icon:ShieldCheck,title:"11. Actualizaciones de esta política",text:["Esta política puede actualizarse cuando Avizor incorpore nuevas funcionalidades o cambie la forma en que utiliza determinada información."]},
];
export default function PrivacyPage(){return <main className="mx-auto max-w-[860px] px-5 py-9 text-[#081a31] sm:px-8 sm:py-12"><header><h1 className="text-[34px] font-bold">Privacidad</h1><span className="mt-3 block h-0.5 w-9 bg-[#168c50]"/><p className="mt-5 text-sm leading-6 text-[#405369]">Tu privacidad es importante. En Avizor cuidamos tu información y te explicamos claramente qué datos utilizamos y para qué.</p></header><div className="mt-6 space-y-3">{sections.map(({Icon,title,text},index)=><Accordion key={title} id={`privacy-${index}`} title={title} icon={<Icon className="h-5 w-5"/>} defaultOpen={index===0}><div className="space-y-3">{text.map(paragraph=><p key={paragraph}>{title==="10. Contacto"&&paragraph==="letsar.software@gmail.com"?<a className="font-semibold text-[#087b4b] hover:underline" href="mailto:letsar.software@gmail.com">{paragraph}</a>:paragraph}</p>)}</div></Accordion>)}</div><p className="mt-6 text-sm text-[#526477]">Última actualización: {PRIVACY_POLICY_LAST_UPDATED}</p></main>}
