import type { LucideIcon } from "lucide-react";
import { Clock3, ExternalLink, LockKeyhole, Mail, MapPin, MessageCircle } from "lucide-react";

export default function ContactPage(){return <main className="mx-auto max-w-[1180px] px-5 py-10 text-[#081a31] sm:px-8 sm:py-12"><div className="grid gap-12 lg:grid-cols-[.82fr_1.18fr] lg:gap-16">
  <section><h1 className="text-[36px] font-bold tracking-tight sm:text-4xl">Contacto</h1><span className="mt-4 block h-0.5 w-10 bg-[#168c50]"/><p className="mt-7 text-xl font-bold text-[#087b4b]">¿Tenés dudas o sugerencias?</p><p className="mt-2 text-base text-[#405369]">Escribinos, nos encanta leerte.</p><div className="mt-9 space-y-3"><ContactCard Icon={Mail} title="Email"><a href="mailto:hola@avizor.com.ar">hola@avizor.com.ar</a></ContactCard><ContactCard Icon={MapPin} title="Ubicación">Tandil, Buenos Aires, Argentina</ContactCard><ContactCard Icon={Clock3} title="Horario de respuesta">24 a 48 horas hábiles</ContactCard></div><a href="https://www.linkedin.com/company/avizor-agtech" target="_blank" rel="noreferrer" className="mt-6 flex min-h-16 items-center gap-4 rounded-xl bg-[#eaf6fc] px-5 text-base font-bold text-[#0876ab]"><span className="flex h-8 w-8 items-center justify-center rounded bg-[#0876ab] text-sm text-white">in</span>Seguinos en LinkedIn<ExternalLink className="ml-auto h-5 w-5"/></a></section>
  <section><h2 className="text-[36px] font-bold tracking-tight sm:text-4xl">Escribinos</h2><span className="mt-4 block h-0.5 w-10 bg-[#168c50]"/><p className="mt-7 text-base text-[#405369]">Contanos cómo podemos ayudarte.</p><form className="mt-8 space-y-6 rounded-2xl border border-[#e0e7e3] bg-white p-5 shadow-[0_6px_20px_rgba(8,26,49,.03)] sm:p-7"><Field label="Nombre (opcional)" placeholder="Tu nombre"/><Field label="Email" placeholder="tu@email.com" type="email"/><label className="block text-sm font-bold">Asunto<select className="mt-3 h-14 w-full rounded-xl border border-[#dce3df] bg-white px-4 text-base font-normal text-[#405369]"><option>¿En qué podemos ayudarte?</option><option>Consulta sobre resultados</option><option>Sugerencia</option><option>Otro</option></select></label><label className="block text-sm font-bold">Mensaje<textarea className="mt-3 min-h-40 w-full resize-y rounded-xl border border-[#dce3df] p-4 text-base font-normal" placeholder="Contanos tu consulta o sugerencia..."/></label><button type="submit" className="flex min-h-14 w-full items-center justify-center gap-3 rounded-xl bg-[#087b4b] text-base font-bold text-white shadow-sm"><MessageCircle className="h-5 w-5"/>Enviar mensaje</button></form><p className="mx-auto mt-6 flex max-w-xl items-center justify-center gap-2 text-center text-sm leading-6 text-[#718093]"><LockKeyhole className="h-4 w-4 shrink-0"/><span>Tu información está segura. No compartimos tus datos con terceros.</span></p></section>
</div></main>}

function ContactCard({Icon,title,children}:{Icon:LucideIcon;title:string;children:React.ReactNode}){return <article className="flex min-h-[128px] items-center gap-5 rounded-2xl border border-[#e0e7e3] bg-white p-5 text-left shadow-[0_4px_16px_rgba(8,26,49,.025)]"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-[#eaf8ef] text-[#087b4b]"><Icon className="h-7 w-7"/></span><div><h2 className="text-base font-bold">{title}</h2><div className="mt-2 text-base leading-6 text-[#405369]">{children}</div></div></article>}
function Field({label,placeholder,type="text"}:{label:string;placeholder:string;type?:string}){return <label className="block text-sm font-bold">{label}<input type={type} className="mt-3 h-14 w-full rounded-xl border border-[#dce3df] px-4 text-base font-normal" placeholder={placeholder}/></label>}
