"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import type { CategoriaResultado, ResultadoConsulta } from "@/types";
import { ArrowLeft, ArrowRight, BookOpen, CalendarDays, Check, CheckCircle2, Cloud, CloudRain, Download, Droplets, Eye, Info, Leaf, MapPin, Share2, ShieldCheck, Snowflake, Sprout, Thermometer, Timer, TriangleAlert } from "lucide-react";
import type { LucideIcon } from "lucide-react";

type Query = { localidad?: string; cultivo?: string; createdAt?: string };
type Mode = "attention" | "clear" | "indeterminate";
type Category = { key: string; name: string; Icon: LucideIcon; color: string; bg: string; status: string; condition?: CategoriaResultado };

const baseCategories = [{ key: "heladas", name: "Heladas", Icon: Cloud, color: "text-[#087b4b]", bg: "bg-green-50" }, { key: "enfermedades_foliares", name: "Enfermedades foliares", Icon: Leaf, color: "text-orange-600", bg: "bg-orange-50" }, { key: "estres_hidrico", name: "Estrés hídrico", Icon: Droplets, color: "text-red-600", bg: "bg-red-50" }, { key: "exceso_hidrico", name: "Exceso hídrico", Icon: CloudRain, color: "text-indigo-700", bg: "bg-indigo-50" }];

function Metadata({ compact = false }: { compact?: boolean }) { return <div className={compact ? "grid grid-cols-4 gap-2 border-y py-4" : "grid gap-5 sm:grid-cols-2"}>{[[CalendarDays,"Período analizado","Últimos 14 días","(07/06 – 20/06)"],[MapPin,"Estación de referencia","Tandil","(Open-Meteo)"],[CheckCircle2,"Cobertura de datos","100 %","Cobertura"],[Timer,"Última actualización","09:30","20/06/2026"]].map(([Icon,label,value,help]) => { const I=Icon as LucideIcon; return <div key={label as string} className={`flex ${compact ? "flex-col items-center text-center" : "gap-3"}`}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-green-50 text-[#087b4b]"><I className="h-4 w-4" /></span><p className="text-[10px] leading-relaxed"><span className={compact ? "hidden" : "block text-[#526477]"}>{label as string}</span><strong className="block text-[#081a31]">{value as string}</strong><span className="text-[#526477]">{help as string}</span></p></div>; })}</div>; }

function ResultChart({ clear = false }: { clear?: boolean }) { return <svg viewBox="0 0 430 180" className="mt-4 w-full" aria-label="Evolución de variables"><line x1="28" y1="145" x2="410" y2="145" stroke="#dfe7e2" /><line x1="28" y1="65" x2="410" y2="65" stroke="#ef5b5b" strokeDasharray="5 4" />{[52,130,205,292,360].map((x,i)=><rect key={x} x={x} y={145-[24,5,18,8,4][i]} width="14" height={[24,5,18,8,4][i]} fill="#438bd5" />)}<polyline points={clear ? "28,70 65,50 105,64 145,76 188,45 230,63 270,55 315,77 360,52 405,65" : "28,142 78,137 122,138 164,105 210,104 260,78 308,63 352,42 405,35"} fill="none" stroke={clear ? "#16824a" : "#1970cf"} strokeWidth="2.5" />{clear && <polyline points="28,112 65,101 105,95 145,108 188,100 230,102 270,91 315,104 360,96 405,105" fill="none" stroke="#e26f13" strokeWidth="2" />}<text x="28" y="165" fontSize="10" fill="#627487">7 Jun</text><text x="375" y="165" fontSize="10" fill="#627487">20 Jun</text></svg>; }

export default function ResultPage() {
  const [result,setResult]=useState<ResultadoConsulta|null>(null); const [query,setQuery]=useState<Query|null>(null); const [loaded,setLoaded]=useState(false);
  useEffect(()=>{ try { const r=sessionStorage.getItem("avizor_resultado"); const q=sessionStorage.getItem("avizor_consulta"); if(r)setResult(JSON.parse(r)); if(q)setQuery(JSON.parse(q)); } finally { setLoaded(true); } },[]);
  const mode: Mode = !result ? "indeterminate" : result.estado_general === "Sin alertas activas" ? "clear" : "attention";
  const categories: Category[] = useMemo(()=>baseCategories.map((base)=>{ const found=result?.categorias.find((item)=>item.nombre===base.key); const status=mode==="clear"?"Sin condiciones detectadas":found?.condicion==="favorable"?"Condiciones favorables":found?.condicion==="moderada"?"Condiciones moderadas":found?"Condiciones desfavorables":base.key==="exceso_hidrico"?"Condiciones favorables":"Sin condiciones detectadas"; return {...base,status,condition:found}; }),[result,mode]);
  const climate=result?.clima_resumen; const metrics=[["Precipitación acumulada",climate?`${climate.lluvia_14d_mm} mm`:"23 mm"],["Días con lluvia",climate?`${climate.dias_lluvia_14d} días`:"2 días"],["Humedad relativa promedio",climate?.humedad_media_14d==null?"78 %":`${climate.humedad_media_14d} %`],["Temperatura media",climate?.temp_media_14d==null?"20.8 °C":`${climate.temp_media_14d} °C`],["Temperatura mínima promedio",climate?.temp_min_14d==null?"9.3 °C":`${climate.temp_min_14d} °C`]];
  if(!loaded)return <main className="min-h-[60vh]" />;
  const title=mode==="attention"?"Atención recomendada":mode==="clear"?"Sin condiciones detectadas":"No fue posible evaluar esta condición"; const description=mode==="attention"?"Se registraron condiciones ambientales que pueden favorecer algunos riesgos agrícolas. Revisá el detalle por categoría y seguí las recomendaciones.":mode==="clear"?"Durante el período analizado no se registraron condiciones ambientales que coincidan con las reglas evaluadas.":"No contamos con datos suficientes o completos para evaluar las reglas agronómicas en este período.";
  return <main className="mx-auto max-w-[1420px] px-4 py-5 text-[#081a31] sm:px-7 lg:py-8"><div className="flex items-center justify-between"><Link href="/consultar" className="inline-flex min-h-11 items-center gap-2 text-xs font-semibold text-[#087b4b]"><ArrowLeft className="h-4 w-4" />Volver a consultar</Link><div className="hidden gap-5 lg:flex"><button onClick={()=>navigator.share?.({title,url:location.href})} className="flex items-center gap-2 text-sm"><Share2 className="h-4 w-4 text-[#087b4b]" />Compartir</button><button onClick={()=>window.print()} className="flex items-center gap-2 text-sm"><Download className="h-4 w-4 text-[#087b4b]" />Descargar PDF</button></div></div>
    <section className="mt-2 rounded-xl border bg-white p-5 lg:grid lg:grid-cols-[1fr_1fr] lg:gap-8 lg:p-7"><div className="flex gap-4"><span className={`flex h-16 w-16 shrink-0 items-center justify-center rounded-full ${mode==="indeterminate"?"bg-blue-50 text-blue-600":"bg-green-50 text-[#087b4b]"}`}>{mode==="attention"?<ShieldCheck className="h-9 w-9" />:mode==="clear"?<CheckCircle2 className="h-9 w-9" />:<CloudRain className="h-9 w-9" />}</span><div><p className="text-[10px] font-bold uppercase tracking-wide text-[#087b4b]">Estado general</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">{title}</h1><p className="mt-3 max-w-xl text-xs leading-relaxed text-[#405369]">{description}</p><Link href="/explicacion-resultado" className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-[#087b4b]">¿Qué significa este resultado? <ArrowRight className="h-3 w-3" /></Link></div></div><div className="mt-5 hidden border-l pl-8 lg:block"><Metadata /></div></section><div className="mt-4 lg:hidden"><Metadata compact /></div>
    {mode==="indeterminate"?<Indeterminate metrics={metrics} />:<><section className="mt-4"><h2 className="text-sm font-bold">Resumen por categoría</h2><div className="mt-3 grid gap-2 lg:grid-cols-4">{categories.map(({key,name,Icon,color,bg,status})=><Link key={key} href={`/resultado/${key}`} className="flex min-h-[72px] items-center gap-3 rounded-xl border bg-white p-4"><span className={`flex h-10 w-10 items-center justify-center rounded-full ${bg} ${color}`}><Icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><strong className="text-xs">{name}</strong><span className={`mt-1 block text-xs font-semibold ${color}`}>{status}</span></span><ArrowRight className={`h-4 w-4 ${color}`} /></Link>)}</div></section><div className="mt-3 grid gap-3 lg:grid-cols-[.9fr_1.15fr_1fr]"><Metrics metrics={metrics} /><section className="rounded-xl border bg-white p-5"><h2 className="text-sm font-bold">{mode==="clear"?"Evolución general de variables clave":"Evolución de precipitación acumulada"}</h2><p className="mt-1 text-[11px] text-[#526477]">Promedios diarios · Últimos 14 días</p><ResultChart clear={mode==="clear"} /><p className="text-xs font-semibold text-[#087b4b]">Ver detalle técnico del gráfico</p></section><section className="rounded-xl border bg-white p-5"><h2 className="text-sm font-bold">{mode==="clear"?"¿Qué significa este resultado?":"Comparación con las reglas"}</h2>{mode==="clear"?<><p className="mt-5 rounded-lg border border-blue-200 bg-blue-50 p-4 text-xs leading-relaxed">Las condiciones ambientales de los últimos 14 días no alcanzaron los umbrales definidos por las reglas agronómicas.</p><h3 className="mt-5 flex gap-2 text-xs font-bold"><Eye className="h-4 w-4 text-[#087b4b]" />Recomendación</h3><p className="mt-3 text-xs leading-relaxed text-[#405369]">Mantener el monitoreo habitual del lote y continuar con las prácticas preventivas.</p></>:<><ul className="mt-4 space-y-4">{categories.map((cat)=><li key={cat.key} className="flex items-center justify-between gap-3 text-xs"><span>{cat.name}</span><strong className={cat.color}>{cat.status}</strong></li>)}</ul><div className="mt-5 rounded-lg bg-green-50 p-4"><h3 className="text-sm font-bold text-[#087b4b]">Recomendación general</h3><p className="mt-2 text-xs leading-relaxed">Monitorear el lote durante los próximos 5 a 7 días y evaluar medidas preventivas.</p></div></>}</section></div></>}
    {mode!=="indeterminate"&&<div className="mt-3 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><SupportCard Icon={BookOpen} title="Fuente y evidencia" items={["Reglas basadas en bibliografía técnica validada.","INTA · Soja: Enfermedades foliares"]}/><SupportCard Icon={Eye} title="Qué observar" items={["Evolución de humedad relativa","Presencia de lluvias pronosticadas","Estado fenológico del cultivo","Condiciones del suelo"]}/><SupportCard Icon={TriangleAlert} title="Limitaciones de esta evaluación" items={["No reemplaza el asesoramiento profesional","Depende de la calidad de los datos","Reglas específicas para soja"]}/><SupportCard Icon={ShieldCheck} title="Calidad de los datos" items={["Fuente: Open-Meteo","Cobertura: 100 %","Período: 14 días completos","Calidad: Alta"]}/></div>}
    <p className="mt-3 flex items-center gap-2 rounded-lg border bg-[#f8faf9] p-3 text-[11px] text-[#526477]"><Info className="h-4 w-4 text-blue-600" />Este resultado describe condiciones ambientales y no el estado sanitario del lote.</p></main>;
}

function Metrics({metrics}:{metrics:string[][]}){return <section className="rounded-xl border bg-white p-5"><div className="flex justify-between"><h2 className="text-sm font-bold">Variables clave (14 días)</h2><span className="text-xs font-semibold text-[#087b4b] lg:hidden">Ver todas</span></div><dl className="mt-4 divide-y">{metrics.map(([label,value])=><div key={label} className="flex justify-between gap-3 py-3 text-xs"><dt className="flex items-center gap-2"><Droplets className="h-4 w-4 text-indigo-600" />{label}</dt><dd className="shrink-0 font-bold">{value}</dd></div>)}</dl></section>}
function SupportCard({Icon,title,items}:{Icon:LucideIcon;title:string;items:string[]}){return <section className="rounded-xl border bg-white p-5"><h2 className="flex gap-2 text-sm font-bold"><Icon className="h-5 w-5 text-[#087b4b]" />{title}</h2><ul className="mt-4 space-y-3">{items.map((item)=><li key={item} className="flex gap-2 text-xs text-[#405369]"><span>›</span>{item}</li>)}</ul></section>}
function Indeterminate({metrics}:{metrics:string[][]}){return <div className="mt-4 grid gap-3 lg:grid-cols-3"><section className="rounded-xl border bg-white p-5"><h2 className="text-sm font-bold">Motivo</h2><p className="mt-4 text-xs leading-relaxed text-[#405369]">No se pudieron evaluar las reglas porque faltan datos completos en una o más variables clave.</p><h3 className="mt-5 text-xs font-bold">Variables con datos insuficientes</h3><p className="mt-3 text-xs text-red-600">Humedad relativa · 4 de 14 días</p><p className="mt-2 text-xs text-orange-600">Precipitación acumulada · 5 de 14 días</p><Link href="/consultar" className="mt-5 inline-flex min-h-11 items-center text-xs font-semibold text-[#087b4b]">Volver a consultar</Link></section><section className="rounded-xl border bg-white p-5"><h2 className="text-sm font-bold">Cobertura de datos</h2><div className="mt-5 space-y-5">{[["Temperatura","100 %","w-full"],["Humedad relativa","29 %","w-[29%]"],["Precipitación","36 %","w-[36%]"]].map(([label,value,width])=><div key={label}><div className="flex justify-between text-xs"><span>{label}</span><strong>{value}</strong></div><div className="mt-2 h-2 rounded bg-slate-100"><div className={`h-2 rounded bg-[#087b4b] ${width}`} /></div></div>)}</div></section><section className="rounded-xl border bg-white p-5"><h2 className="text-sm font-bold">Información importante</h2><p className="mt-4 text-xs leading-relaxed text-[#405369]">Un análisis confiable requiere al menos el 70 % de los datos en cada variable durante el período analizado.</p><Link href="/metodologia" className="mt-4 inline-flex text-xs font-semibold text-[#087b4b]">Ver metodología</Link></section></div>}
