import { ExternalLink, FileText, Info } from "lucide-react";
const sources=[
 {title:"INTA. Manual de enfermedades de fin de ciclo en soja",meta:"INTA Ediciones, 2022.",tag:"Enfermedades foliares",action:"Ver PDF"},
 {title:"FAO. Water and agriculture: Facing water scarcity",meta:"FAO Water Reports, 2021.",tag:"Estrés hídrico",action:"Ver PDF"},
 {title:"Servicio Meteorológico Nacional. Normales climáticas",meta:"Serie 1981–2010.",tag:"Clima",action:"Ver sitio"},
 {title:"Ciampitti, I. A. et al. Manejo del cultivo de soja",meta:"EEA INTA Pergamino, 2019.",tag:"Soja",action:"Ver PDF"},
 {title:"Magurris, R. et al. SEVWA risk model for foliar diseases",meta:"Plant Pathology, 2025.",tag:"Enfermedades foliares",action:"DOI"},
 {title:"Universidad Nacional de Córdoba. Guía de heladas en cultivos",meta:"FCA UNC, 2020.",tag:"Heladas",action:"Ver PDF"},
];
const tabs=["Todas","Enfermedades foliares","Heladas","Estrés hídrico","Exceso hídrico"];
export default function Bibliography(){return <main className="mx-auto max-w-[1180px] px-5 py-9 text-[#081a31] sm:px-8 sm:py-12"><header><h1 className="text-[34px] font-bold">Bibliografía</h1><span className="mt-3 block h-0.5 w-9 bg-[#168c50]"/><p className="mt-5 max-w-2xl text-sm leading-6 text-[#405369]">Las reglas agronómicas utilizadas por Avizor se basan en publicaciones técnicas y científicas de referencia.</p></header><div className="mt-6 flex flex-wrap gap-x-7 gap-y-3 border-b border-[#e4eae6]">{tabs.map((tab,index)=><button key={tab} className={`border-b-2 px-1 pb-3 text-xs font-semibold ${index===0?"border-[#087b4b] text-[#087b4b]":"border-transparent text-[#405369]"}`}>{tab}</button>)}</div><section className="mt-5 grid gap-3 lg:grid-cols-2">{sources.map(source=><article key={source.title} className="rounded-2xl border border-[#e0e7e3] bg-white p-4 shadow-[0_4px_16px_rgba(8,26,49,.025)]"><div className="flex gap-4"><FileText className="h-7 w-7 shrink-0 text-[#087b4b]"/><div><h2 className="text-sm font-bold leading-5">{source.title}</h2><p className="mt-1 text-xs text-[#526477]">{source.meta}</p></div></div><div className="mt-4 flex items-center justify-between gap-3 pl-11"><span className="rounded-md bg-green-50 px-3 py-1.5 text-[11px] text-[#087b4b]">{source.tag}</span><button className="inline-flex min-h-9 items-center gap-2 rounded-xl border px-4 text-xs font-semibold text-[#087b4b]">{source.action}<ExternalLink className="h-3.5 w-3.5"/></button></div></article>)}</section><p className="mt-5 flex gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-xs leading-5 text-[#6b5524]"><Info className="h-5 w-5 shrink-0"/>Las reglas se revisan y actualizan periódicamente en base a nueva evidencia técnica y validación con especialistas.</p></main>}
