"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ChevronRight, Cloud, Download, Filter, History, Leaf, Plus, Sprout } from "lucide-react";
import { PageIntro, PublicPage } from "@/components/PublicPage";
import { SEVERITY_TONES } from "@/components/results/shared";

type Entry={localidad?:string;cultivo?:string;createdAt?:string;estado?:string;categoria?:string;resumen?:string;share_token?:string;result?:unknown};
const color=(state:string)=>state==="Atención recomendada"?SEVERITY_TONES.attention.text:state==="Monitoreo preventivo sugerido"?SEVERITY_TONES.monitor.text:state==="Sin alertas activas"?SEVERITY_TONES.calm.text:SEVERITY_TONES.neutral.text;
export default function HistoryPage(){const[entries,setEntries]=useState<Entry[]>([]);useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem("avizor_historial")||"[]");setEntries(stored)}catch{setEntries([])}},[]);return <PublicPage><PageIntro title="Historial de consultas" description="Revisá tus consultas anteriores y el estado de las condiciones ambientales." action={{label:"Nueva consulta",href:"/consultar"}} />
  <div className="mt-5 hidden items-end gap-3 rounded-xl border bg-white p-4 lg:flex"><label className="text-xs">Localidad<select className="mt-2 block h-10 rounded-lg border px-3"><option>Todas</option></select></label><label className="text-xs">Categoría<select className="mt-2 block h-10 rounded-lg border px-3"><option>Todas</option></select></label><label className="text-xs">Estado<select className="mt-2 block h-10 rounded-lg border px-3"><option>Todos</option></select></label><label className="text-xs">Período<select className="mt-2 block h-10 rounded-lg border px-3"><option>Últimos 30 días</option></select></label><button className="ml-auto flex h-10 items-center gap-2 rounded-lg border px-4 text-xs"><Download className="h-4 w-4" />Exportar</button></div>
  <div className="mt-5 flex items-center justify-between lg:hidden"><h2 className="text-2xl font-bold">Historial</h2><button className="flex h-10 items-center gap-2 rounded-lg border px-3 text-xs"><Filter className="h-4 w-4" />Filtros</button></div>
  {entries.length?<><div className="mt-4 hidden overflow-hidden rounded-xl border bg-white lg:block"><table className="w-full text-left text-xs"><thead className="bg-[#f8faf9] text-[#526477]"><tr>{["Fecha","Localidad","Categoría principal","Estado general","Resumen de condiciones","Fuente de datos",""].map((h)=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{entries.map((entry,index)=>{const state=entry.estado||"Indeterminado";return <tr key={`${entry.createdAt}-${index}`} className="border-t"><td className="px-4 py-4">{entry.createdAt?new Date(entry.createdAt).toLocaleString("es-AR"):"—"}</td><td className="px-4 py-4">{entry.localidad||"Tandil, BA"}</td><td className="px-4 py-4">{entry.categoria||"Soja"}</td><td className={`px-4 py-4 font-bold ${color(state)}`}>{state}</td><td className="px-4 py-4">{entry.resumen||"Consulta climática"}</td><td className="px-4 py-4">Open-Meteo</td><td className="px-4 py-4"><Link href="/resultado" onClick={()=>entry.result&&sessionStorage.setItem("avizor_resultado",JSON.stringify(entry.result))} className="rounded border px-3 py-2 font-semibold text-[#087b4b]">Ver detalle</Link></td></tr>})}</tbody></table></div><div className="mt-4 space-y-2 lg:hidden">{entries.map((entry,index)=>{const state=entry.estado||"Indeterminado";return <Link href="/resultado" onClick={()=>entry.result&&sessionStorage.setItem("avizor_resultado",JSON.stringify(entry.result))} key={`${entry.createdAt}-${index}`} className="flex items-center gap-3 rounded-xl border bg-white p-4"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-green-50 text-[#087b4b]"><Cloud className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block text-[10px] text-[#526477]">{entry.createdAt?new Date(entry.createdAt).toLocaleString("es-AR"):"—"}</span><strong className="mt-1 block text-xs">{entry.localidad||"Tandil, BA"} · {entry.cultivo||"Soja"}</strong><span className={`mt-1 block text-xs font-bold ${color(state)}`}>{state}</span></span><ChevronRight className="h-4 w-4" /></Link>})}</div></>:<section className="mt-7 rounded-xl border border-dashed bg-white p-8 text-center"><History className="mx-auto h-10 w-10 text-[#087b4b]" /><h2 className="mt-4 font-bold">Todavía no hay consultas</h2><p className="mt-2 text-sm text-[#526477]">Tus próximas consultas aparecerán en este dispositivo.</p><Link href="/consultar" className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-lg border border-green-300 px-5 text-sm font-semibold text-[#087b4b]"><Plus className="h-4 w-4" />Nueva consulta</Link></section>}<p className="mt-6 rounded-lg bg-green-50 p-4 text-xs text-[#087b4b]">Cada consulta se guarda automáticamente en este dispositivo. Los datos climáticos se actualizan cada hora.</p></PublicPage>}

