"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ChevronDown, CloudRain, Info, Leaf, Loader2, MapPin, Sprout, Thermometer, Wind } from "lucide-react";

export default function HeroSection() {
  const router = useRouter(); const [localidad, setLocalidad] = useState("Tandil, Buenos Aires"); const [cultivo, setCultivo] = useState("soja"); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  function sessionId() { const current = localStorage.getItem("avizor_session_id"); if (current) return current; const id = crypto.randomUUID(); localStorage.setItem("avizor_session_id", id); return id; }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!localidad.trim()) { setError("Ingresá una localidad."); return; } setLoading(true); setError(""); try { const response = await fetch("/api/consulta", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ localidad, cultivo, session_id: sessionId() }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "No pudimos completar la consulta."); return; } const query = { localidad, cultivo, createdAt: new Date().toISOString(), estado: data.estado_general, categoria: data.categorias?.[0]?.nombre, resumen: data.categorias?.[0]?.causas?.join(", ") }; sessionStorage.setItem("avizor_resultado", JSON.stringify(data)); sessionStorage.setItem("avizor_consulta", JSON.stringify(query)); const history = JSON.parse(localStorage.getItem("avizor_historial") || "[]"); localStorage.setItem("avizor_historial", JSON.stringify([query, ...history].slice(0, 20))); router.push("/resultado"); } catch { setError("No pudimos obtener los datos climáticos. Intentá nuevamente en unos minutos."); } finally { setLoading(false); } }
  return <main className="mx-auto min-h-[calc(100vh-8rem)] max-w-[980px] px-5 py-8 text-[#081a31] sm:px-8 sm:py-12"><div className="grid gap-8 lg:grid-cols-[1fr_360px] lg:items-center"><section><h1 className="text-2xl font-bold sm:text-3xl">Realizá una consulta</h1><p className="mt-3 text-sm text-[#405369]">Elegí tu ubicación y cultivo para comenzar.</p><form onSubmit={submit} className="mt-8 space-y-5"><div><label htmlFor="crop" className="mb-2 block text-xs font-semibold text-[#526477]">Cultivo</label><div className="relative"><Sprout className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#087b4b]" /><select id="crop" value={cultivo} onChange={(event) => setCultivo(event.target.value)} className="h-12 w-full appearance-none rounded-lg border bg-white pl-11 pr-10 text-sm"><option value="soja">Soja</option></select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2" /></div></div><div><label htmlFor="place" className="mb-2 block text-xs font-semibold text-[#526477]">Localidad</label><div className="relative"><MapPin className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#087b4b]" /><input id="place" value={localidad} onChange={(event) => setLocalidad(event.target.value)} className="h-12 w-full rounded-lg border bg-white pl-11 pr-4 text-sm" /></div></div>{error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}<button disabled={loading} className="flex min-h-12 w-full items-center justify-center rounded-lg bg-[#087b4b] font-semibold text-white disabled:opacity-60">{loading ? <><Loader2 className="mr-2 h-5 w-5 animate-spin" />Consultando…</> : "Consultar"}</button></form></section><aside className="relative mx-auto flex h-64 w-64 items-center justify-center rounded-full bg-[#f3f8f5] lg:h-72 lg:w-72"><Sprout className="h-28 w-28 text-[#087b4b]" strokeWidth={1.4} /><span className="absolute left-3 top-24 flex h-14 w-14 items-center justify-center rounded-full border bg-white text-[#e27235]"><Thermometer /></span><span className="absolute right-7 top-5 flex h-14 w-14 items-center justify-center rounded-full border bg-white text-[#3688c7]"><CloudRain /></span><span className="absolute right-0 top-28 flex h-14 w-14 items-center justify-center rounded-full border bg-white text-[#477b9a]"><Wind /></span></aside></div><section className="mt-8 flex gap-3 rounded-xl border bg-[#f8faf9] p-4"><Info className="h-5 w-5 shrink-0 text-[#087b4b]" /><div><h2 className="text-sm font-bold">Sin cuenta, sin complicaciones</h2><p className="mt-1 text-xs leading-relaxed text-[#526477]">Hacé tu consulta sin registrarte. Si querés recibir novedades, podés dejarnos tu email al final.</p></div></section><p className="mt-5 text-center text-[11px] text-[#718093]">Avizor no diagnostica ni reemplaza el asesoramiento profesional. La información es de carácter orientativo.</p></main>;
}

