import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, BookOpen, CloudSun, Database, MapPin, Search, ShieldCheck } from "lucide-react";

const problems=[{Icon:MapPin,title:"Clima disperso y confuso"},{Icon:BookOpen,title:"Información sin contexto"},{Icon:Search,title:"Difícil de interpretar"},{Icon:BarChart3,title:"Poca claridad para decidir"}];
const steps=["Ingresás tu ubicación y cultivo","Analizamos las condiciones de los últimos 14 días","Aplicamos reglas agronómicas validadas","Obtenés una señal simple y recomendaciones accionables"];
const values=[{Icon:CloudSun,label:"Datos climáticos de calidad"},{Icon:BookOpen,label:"Reglas agronómicas validadas"},{Icon:ShieldCheck,label:"Metodología transparente"},{Icon:Database,label:"Información simple y accionable"}];

export default function HomeLanding(){return <main className="text-[#081a31]">
  <section className="relative min-h-[525px] overflow-hidden sm:min-h-[430px]"><Image src="/campo-hojas.png" alt="Cultivo de soja al amanecer" fill priority className="object-cover object-[68%_center] sm:object-[68%_center]"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(255,255,255,.98)_0%,rgba(255,255,255,.90)_46%,rgba(255,255,255,.10)_82%)] sm:bg-[linear-gradient(90deg,rgba(255,255,255,.98)_0%,rgba(255,255,255,.91)_43%,rgba(255,255,255,.08)_72%)]"/><div className="relative mx-auto flex min-h-[525px] max-w-[1440px] items-center px-5 py-10 sm:min-h-[430px] sm:px-8 sm:py-12 lg:px-14"><div className="w-full max-w-[530px]"><h1 className="text-[40px] font-bold leading-[1.08] tracking-tight sm:text-5xl">La señal<br/>antes del problema.</h1><p className="mt-5 max-w-[295px] text-sm leading-6 text-[#263a4d] sm:max-w-none">Avizor identifica condiciones ambientales que pueden favorecer determinados riesgos agrícolas y traduce esa información en recomendaciones simples para el productor.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/consultar" className="inline-flex min-h-12 items-center justify-center rounded-lg bg-[#087b4b] px-6 text-sm font-bold text-white">Realizar una consulta</Link><Link href="/metodologia" className="inline-flex min-h-12 items-center justify-center rounded-lg border border-[#53ad7b] bg-white/90 px-6 text-sm font-bold text-[#087b4b]">Cómo funciona</Link></div></div></div></section>
  <section className="mx-auto max-w-[1440px] px-5 py-9 sm:px-8 lg:px-14"><h2 className="text-[22px] font-bold">¿Cuál es el problema?</h2><p className="mt-2 max-w-2xl text-sm leading-5 text-[#263a4d]">El productor consulta múltiples fuentes desconectadas para responder una pregunta simple: ¿qué tengo que preocuparme hoy por mi cultivo?</p><div className="mt-5 grid gap-0 sm:grid-cols-2 sm:gap-3 lg:grid-cols-4">{problems.map(({Icon,title})=><article key={title} className="flex min-h-14 items-center gap-4 rounded-xl border border-[#dfe6e2] bg-white px-4 py-3 shadow-[0_3px_10px_rgba(8,26,49,.03)]"><Icon className="h-7 w-7 shrink-0 text-[#2886c2]"/><h3 className="text-sm font-semibold">{title}</h3></article>)}</div></section>
  <section className="bg-white sm:border-y sm:bg-[#fafcfb]"><div className="mx-auto max-w-[1440px] px-5 py-6 sm:px-8 sm:py-9 lg:px-14"><h2 className="text-[22px] font-bold">¿Cómo funciona Avizor?</h2><div className="mt-6 grid gap-0 md:grid-cols-4 md:gap-5">{steps.map((step,index)=><article key={step} className="relative flex min-h-[68px] gap-4 md:min-h-0"><span className="relative z-10 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#087b4b] text-sm font-bold text-white">{index+1}</span><p className="pt-1 text-sm font-semibold leading-5">{step}</p>{index<3&&<><span className="absolute bottom-0 left-[15px] top-8 w-px bg-[#b9ddc8] md:hidden"/><ArrowRight className="absolute -right-3 hidden h-4 w-4 text-[#83b89a] md:block"/></>}</article>)}</div></div></section>
  <section className="mx-auto max-w-[1440px] px-5 py-9 sm:px-8 lg:px-14"><div className="rounded-2xl border border-[#cfe1d6] bg-[#f8fbf9] p-5 sm:p-6"><h2 className="text-xl font-bold">Tecnología + conocimiento agronómico</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#263a4d]">Combinamos datos climáticos de múltiples fuentes con reglas agronómicas validadas por especialistas para generar señales confiables y útiles.</p><div className="mt-5 grid gap-0 sm:grid-cols-2 sm:gap-4 lg:grid-cols-4">{values.map(({Icon,label})=><div key={label} className="flex min-h-12 items-center gap-3 rounded-xl border border-[#dfe8e2] bg-white px-4 text-sm font-semibold"><Icon className="h-5 w-5 shrink-0 text-[#087b4b]"/>{label}</div>)}</div></div></section>
</main>}
