"use client";

import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BookOpen, CircleUserRound, Clock3, Ellipsis, FileText, History, Home, Info, Mail, Search, ShieldCheck, X } from "lucide-react";

const main = [{ label: "Inicio", href: "/", Icon: Home }, { label: "Consultar", href: "/consultar", Icon: Search }, { label: "Historial", href: "/historial", Icon: History }, { label: "Metodología", href: "/metodologia", Icon: BookOpen }];
const more = [{ label: "Sobre Avizor", href: "/sobre-avizor", Icon: CircleUserRound }, { label: "Bibliografía", href: "/bibliografia", Icon: FileText }, { label: "Alcance y limitaciones", href: "/alcance-limitaciones", Icon: Info }, { label: "Privacidad", href: "/privacidad", Icon: ShieldCheck }, { label: "Novedades", href: "/novedades", Icon: Clock3 }, { label: "Contacto", href: "/contacto", Icon: Mail }];

export default function MobileBottomNavigation() {
  const pathname = usePathname(); const [open, setOpen] = useState(false); const consultationActive = pathname.startsWith("/consultar") || pathname.startsWith("/resultado");
  return <><nav aria-label="Navegación principal móvil" className="fixed inset-x-0 bottom-0 z-50 border-t border-[#d9e4dd] bg-white/96 pb-[env(safe-area-inset-bottom)] shadow-[0_-8px_24px_rgba(7,29,54,.08)] backdrop-blur lg:hidden"><div className="mx-auto grid h-16 max-w-xl grid-cols-5">{main.map(({ label, href, Icon }) => { const active = href === "/consultar" ? consultationActive : pathname.startsWith(href) && (href !== "/" || pathname === "/"); return <Link key={href} href={href} aria-current={active ? "page" : undefined} className={`flex min-w-0 flex-col items-center justify-center gap-1 px-1 text-[9px] font-semibold ${active ? "text-[#087b4b]" : "text-[#53687a]"}`}><Icon className="h-5 w-5" strokeWidth={active ? 2.5 : 1.8} /><span>{label}</span></Link>; })}<button onClick={() => setOpen(true)} aria-expanded={open} aria-controls="more-navigation" className="flex flex-col items-center justify-center gap-1 text-[9px] font-semibold text-[#53687a]"><Ellipsis className="h-5 w-5" /><span>Más</span></button></div></nav>{open && <div className="fixed inset-0 z-[60] bg-[#071d36]/35 lg:hidden" onClick={() => setOpen(false)}><section id="more-navigation" role="dialog" aria-modal="true" aria-label="Más secciones" className="absolute inset-x-0 bottom-0 rounded-t-2xl bg-white p-5 pb-[calc(1.25rem+env(safe-area-inset-bottom))]" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><h2 className="font-bold">Más secciones</h2><button onClick={() => setOpen(false)} aria-label="Cerrar" className="flex h-11 w-11 items-center justify-center rounded-full border"><X className="h-5 w-5" /></button></div><nav className="mt-3 grid grid-cols-2 gap-2">{more.map(({ label, href, Icon }) => <Link key={href} href={href} onClick={() => setOpen(false)} className="flex min-h-14 items-center gap-3 rounded-xl border p-3 text-xs font-semibold"><Icon className="h-5 w-5 text-[#087b4b]" />{label}</Link>)}</nav></section></div>}</>;
}
