import Image from "next/image";
import { BarChart3, CalendarDays, Code2, Cpu, Database, Leaf, Lightbulb, MapPin, MousePointer2, Pencil, Search, Server, Settings, ShieldCheck, Sprout, UserRoundCheck } from "lucide-react";
import { ScopeDisclaimer } from "@/components/PublicPage";

const principles = [
  { Icon: ShieldCheck, title: "Basado en ciencia", text: "Usamos datos reales y reglas agronómicas técnicas validadas por especialistas." },
  { Icon: Lightbulb, title: "Claro y simple", text: "Creamos información de calidad que todos pueden entender y aplicar." },
  { Icon: UserRoundCheck, title: "Siempre orientados", text: "Nos comprometemos a mantener confiable y actualizado el conocimiento agronómico." },
];
const people = [
  { name: "Andrea Alvarez Zunino", role: "Co-fundadora · Frontend Developer · Producto & Desarrollo de Negocio", text: "Dirección del producto, desarrollo frontend, calidad y coordinación general de Avizor.", icon: Code2, linkedin: "https://www.linkedin.com/in/andrea-alvarez-zunino" },
  { name: "Ezequiel Romeo", role: "Co-fundador · Full Stack & AI Engineer", text: "Desarrollo de la plataforma, arquitectura e integración de soluciones de inteligencia artificial.", icon: Server, linkedin: "https://www.linkedin.com/in/ezequiel-romeo/" },
  { name: "Natali Lázaro", role: "Ingeniera Agrónoma", text: "Validación de criterios agronómicos y conocimiento técnico aplicado al motor de señales.", icon: Search, linkedin: "https://www.linkedin.com/in/natali-lazzaro-16702738/" },
  { name: "Laura Alvarez Zunino", role: "UX/UI Designer", text: "Investigación, experiencia de usuario y diseño de las interfaces de Avizor para que la información sea clara, intuitiva y útil.", icon: MousePointer2, linkedin: "https://www.linkedin.com/in/lauraalvarezzunino/" },
  { name: "Román Meclazke", role: "Backend & AI Engineer", text: "Backend, arquitectura e implementación de agentes y soluciones de inteligencia artificial.", icon: Settings, linkedin: "https://www.linkedin.com/in/roman-meclazcke/" },
  { name: "Santiago Pereira", role: "Frontend Developer · Producto & Desarrollo de Negocio", text: "Desarrollo de la experiencia pública y acompañamiento en producto, vinculación y generación de nuevas oportunidades.", icon: BarChart3, linkedin: "https://www.linkedin.com/in/santiago-pereira-994229244/" },
];
const disciplines = [{ Icon: Leaf, label: "Producto" }, { Icon: Cpu, label: "Tecnología & IA" }, { Icon: Sprout, label: "Agronomía" }, { Icon: Pencil, label: "Diseño" }];

export default function AboutPage() {
  return <main className="mx-auto max-w-[1440px] px-5 py-9 text-[#081a31] sm:px-8 sm:py-12">
    <section className="grid gap-7 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#087b4b]">Sobre Avizor</p><h1 className="mt-4 max-w-[570px] text-[30px] font-bold leading-[1.14] tracking-tight [text-wrap:balance] sm:text-[34px] lg:text-[42px]">Tecnología y conocimiento al servicio del productor</h1><span className="mt-5 block h-0.5 w-10 bg-[#168c50]" /><p className="mt-6 max-w-[540px] text-[15px] leading-7 text-[#405369] [text-wrap:pretty] lg:text-sm lg:leading-6">Avizor nace para acercar información climática y conocimiento agronómico de forma simple, clara y confiable.</p><p className="mt-4 max-w-[560px] text-[15px] leading-7 text-[#405369] [text-wrap:pretty] lg:text-sm lg:leading-6">Nuestro objetivo es ayudar a tomar decisiones informadas observando las condiciones ambientales que pueden coincidir con riesgos para tus cultivos.</p></div><div className="relative min-h-[195px] overflow-hidden rounded-2xl sm:min-h-[330px]"><Image src="/campo-hojas.png" alt="Cultivo de soja al amanecer" fill priority className="object-cover object-center" sizes="(min-width:1024px) 540px,100vw" /></div></section>
    <section className="mt-5 grid gap-3 md:mt-8 md:grid-cols-3" aria-label="Principios de Avizor">{principles.map(({ Icon, title, text }) => <article key={title} className="flex min-h-[112px] gap-4 rounded-xl border border-[#e0e8e3] bg-white p-4 shadow-[0_5px_18px_rgba(8,26,49,.025)]"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#edf7f0] text-[#087b4b]"><Icon className="h-6 w-6" /></span><div><h2 className="text-base font-bold">{title}</h2><p className="mt-2 text-sm leading-5 text-[#405369]">{text}</p></div></article>)}</section>
    <section className="mt-6 rounded-xl border border-[#b9dec8] bg-[linear-gradient(135deg,#fbfdfb,#f4f9f5)] p-4 sm:mt-8 sm:p-8"><h2 className="text-[28px] font-bold leading-tight sm:text-[32px]">Detrás de Avizor</h2><p className="mt-1 text-sm leading-6 text-[#405369] sm:text-base">Tecnología, agronomía, diseño y desarrollo de producto trabajando juntos para transformar datos ambientales en información útil para el productor.</p><div className="mt-7 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{people.map((person) => <TeamCard key={person.name} {...person} />)}</div><div className="mt-6 grid border-t border-[#bdd9c6] pt-4 sm:mt-6 sm:grid-cols-4 sm:pt-5">{disciplines.map(({ Icon, label }, index) => <div key={label} className={`flex items-center justify-center gap-3 py-3 text-sm font-bold text-[#087b4b] sm:py-1 ${index ? "sm:border-l sm:border-[#cfe2d4]" : ""}`}><Icon className="h-7 w-7 stroke-[1.8]" />{label}</div>)}</div></section>
    <section className="mt-6 rounded-xl border border-[#d5e4d9] bg-white px-5 py-5 sm:mt-5 sm:grid sm:grid-cols-[1.35fr_1fr] sm:items-center sm:gap-8 sm:px-8 sm:py-6"><div><h2 className="text-2xl font-bold">El proyecto</h2><span className="mt-2 block h-0.5 w-10 bg-[#168c50]" /><p className="mt-3 max-w-[720px] text-sm leading-5 text-[#526477]">Avizor es un proyecto en constante evolución. Combinamos datos climáticos, inteligencia artificial y rigor agronómico validado por especialistas para generar señales accionables, que le ayuden al productor a anticiparse.</p></div><div className="mt-5 grid grid-cols-3 divide-x divide-[#d8e3dc] border-t border-[#d8e3dc] pt-5 sm:mt-0 sm:border-t-0 sm:pt-0"><ProjectMetric Icon={CalendarDays} value="2026" label="Año de inicio" /><ProjectMetric Icon={MapPin} value="+150" label="Localidades cubiertas" /><ProjectMetric Icon={Leaf} value="1" label="Cultivo inicial: soja" /></div></section>
    <ScopeDisclaimer />
  </main>;
}

function TeamCard({ name, role, text, icon: Icon, linkedin }: typeof people[number]) { return <article className="flex flex-col rounded-xl border border-[#d4e3dc] bg-white/70 p-3.5 shadow-[0_3px_13px_rgba(8,26,49,.02)] md:min-h-[205px] md:p-5"><div className="flex items-center gap-3 md:grid md:grid-cols-[128px_minmax(0,1fr)] md:gap-4"><TeamIllustration Icon={Icon} /><div className="min-w-0"><h3 className="text-base font-bold leading-5">{name}</h3><p className="mt-1 text-sm font-bold leading-5 text-[#087b4b] md:mt-2">{role}</p><p className="mt-3 hidden text-sm leading-5 text-[#526477] md:block">{text}</p></div></div><p className="mt-3 text-sm leading-5 text-[#526477] md:hidden">{text}</p><a href={linkedin} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-8 items-center gap-1.5 text-xs font-medium text-[#087b4b] hover:underline md:mt-auto md:min-h-9 md:gap-2 md:pt-4 md:text-sm"><span className="flex h-4 w-4 items-center justify-center rounded-[3px] bg-[#087b4b] text-[9px] font-bold text-white md:h-5 md:w-5 md:text-[11px]">in</span>Ver perfil en LinkedIn</a></article>; }
function TeamIllustration({ Icon }: { Icon: typeof Code2 }) { return <div className="relative flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-full bg-[#edf7ef] text-[#123c4d] md:h-32 md:w-32"><span className="absolute bottom-2 left-2 h-3.5 w-1.5 rotate-[-30deg] rounded-full bg-[#58ac6e] md:bottom-4 md:left-4 md:h-8 md:w-3" /><span className="absolute bottom-2 right-2 h-4 w-1.5 rotate-[35deg] rounded-full bg-[#7bc788] md:bottom-5 md:right-5 md:h-10 md:w-3" /><Icon className="relative z-10 h-7 w-7 stroke-[1.6] md:h-16 md:w-16" /></div>; }
function ProjectMetric({ Icon, value, label }: { Icon: typeof Database; value: string; label: string }) { return <div className="text-center"><Icon className="mx-auto h-8 w-8 text-[#087b4b]" /><p className="mt-1 text-lg font-bold">{value}</p><p className="mt-0.5 text-[10px] uppercase leading-4 tracking-wide text-[#526477]">{label}</p></div>; }
