import Image from "next/image";
import { BarChart3, BookOpen, CalendarDays, Cpu, Database, Leaf, Lightbulb, MapPin, ShieldCheck, Sprout, UserRoundCheck } from "lucide-react";
import { ScopeDisclaimer } from "@/components/PublicPage";

const principles=[
  {Icon:ShieldCheck,title:"Basado en ciencia",text:"Usamos datos reales y reglas agronómicas técnicas validadas por especialistas."},
  {Icon:Lightbulb,title:"Claro y simple",text:"Creamos información de calidad que todos pueden entender y aplicar."},
  {Icon:UserRoundCheck,title:"Siempre orientados",text:"Nos comprometemos a mantener confiable y actualizado el conocimiento agronómico."},
];
const people=[
  {image:"/sobre-avizor-andrea.svg",name:"Andrea Alvarez Zunino",linkedin:"https://www.linkedin.com/in/andrea-alvarez-zunino",role:"Fundadora · Producto & Desarrollo",text:"Creadora de Avizor. Lidera la estrategia del producto, el análisis funcional y el desarrollo de la plataforma. Su objetivo es acercar herramientas tecnológicas simples que ayuden al productor a tomar mejores decisiones en el campo."},
  {image:"/sobre-avizor-ezequiel.svg",name:"Ezequiel Romeo",linkedin:"https://www.linkedin.com/in/ezequiel-romeo/",role:"Arquitectura de Software & IA",text:"Diseña la arquitectura técnica de Avizor y desarrolla las soluciones que integran datos climáticos, reglas agronómicas e inteligencia artificial. Trabaja en la evolución tecnológica de la plataforma y en futuras capacidades inteligentes."},
  {image:"/sobre-avizor-natali.svg",name:"Natali Lazzaro",linkedin:"https://www.linkedin.com/in/natali-lazzaro-16702738/",role:"Especialista Agronómica",text:"Ingeniera Agrónoma del Laboratorio Agropecuario Horizonte. Lidera la validación técnica del conocimiento agronómico de Avizor, revisando cada regla, metodología y recomendación para asegurar que la información sea consistente con la evidencia y aplicable en el campo."},
];
const disciplines=[{Icon:Sprout,label:"Agro"},{Icon:Cpu,label:"Tecnología"},{Icon:ShieldCheck,label:"Ciencia de datos"},{Icon:BarChart3,label:"Clima"},{Icon:Leaf,label:"Cultivos"}];

export default function AboutPage(){return <main className="mx-auto max-w-[1180px] px-5 py-9 text-[#081a31] sm:px-8 sm:py-12">
  <section className="grid gap-7 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#087b4b]">Sobre Avizor</p><h1 className="mt-4 max-w-[570px] text-[30px] font-bold leading-[1.14] tracking-tight [text-wrap:balance] sm:text-[34px] lg:text-[42px]">Tecnología y conocimiento al servicio del productor</h1><span className="mt-5 block h-0.5 w-10 bg-[#168c50]"/><p className="mt-6 max-w-[540px] text-[15px] leading-7 text-[#405369] [text-wrap:pretty] lg:text-sm lg:leading-6">Avizor nace para acercar información climática y conocimiento agronómico de forma simple, clara y confiable.</p><p className="mt-4 max-w-[560px] text-[15px] leading-7 text-[#405369] [text-wrap:pretty] lg:text-sm lg:leading-6">Nuestro objetivo es ayudar a tomar decisiones informadas observando las condiciones ambientales que pueden coincidir con riesgos para tus cultivos.</p></div><div className="relative min-h-[195px] overflow-hidden rounded-2xl sm:min-h-[330px]"><Image src="/campo-hojas.png" alt="Cultivo de soja al amanecer" fill priority className="object-cover object-center" sizes="(min-width:1024px) 540px,100vw"/></div></section>
  <section className="mt-5 grid gap-3 md:mt-8 md:grid-cols-3" aria-label="Principios de Avizor">{principles.map(({Icon,title,text})=><article key={title} className="flex min-h-[112px] gap-4 rounded-xl border border-[#e0e8e3] bg-white p-4 shadow-[0_5px_18px_rgba(8,26,49,.025)]"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#edf7f0] text-[#087b4b]"><Icon className="h-6 w-6"/></span><div><h2 className="text-base font-bold">{title}</h2><p className="mt-2 text-sm leading-5 text-[#405369]">{text}</p></div></article>)}</section>
  <section className="mt-6 rounded-2xl border border-[#dfe8e2] bg-white p-5 sm:mt-8 sm:bg-[linear-gradient(135deg,#f8fbf8,#f2f7f3)] sm:p-8"><h2 className="text-2xl font-bold">Detrás de Avizor</h2><p className="mt-2 max-w-none text-sm font-semibold leading-6 text-[#087b4b]">Tecnología, desarrollo de producto y conocimiento agronómico trabajando juntos para transformar datos ambientales en información útil para el productor.</p><div className="mt-6 grid lg:grid-cols-[1.1fr_1fr_1fr_1fr] lg:gap-7"><div className="about-team-illustration items-center justify-center border-r border-[#d9e5dd] pr-7"><Image src="/sobre-avizor-lab.svg" alt="Tecnología y monitoreo agrícola de Avizor" width={430} height={386} className="about-team-image h-auto w-full max-w-[270px]" style={{maxWidth:270}}/></div>{people.map(person=><article key={person.name} className="grid grid-cols-[68px_minmax(0,1fr)] gap-3 border-b border-[#dfe5e1] py-5 last:border-0 lg:flex lg:h-full lg:flex-col lg:items-start lg:border-0 lg:py-0"><Image src={person.image} alt={`Ilustración de ${person.name}`} width={96} height={96} className="h-16 w-16 sm:h-20 sm:w-20 lg:h-24 lg:w-24"/><div className="flex min-w-0 flex-1 flex-col"><h3 className="text-base font-bold leading-5">{person.name}</h3><p className="mt-1 text-xs font-bold text-[#087b4b]">{person.role}</p><p className="mt-3 text-xs leading-5 text-[#405369]">{person.text}</p><a href={person.linkedin} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-10 flex-wrap items-center gap-2 lg:mt-auto lg:pt-4 text-xs font-bold text-[#087b4b] hover:underline"><span className="flex h-5 w-5 items-center justify-center rounded-sm bg-[#087b4b] text-[10px] font-bold text-white">in</span>Ver perfil en LinkedIn</a></div></article>)}</div><div className="mt-6 grid grid-cols-5 gap-2 rounded-xl border border-[#dce6e0] bg-[#f8faf9] px-2 py-4 sm:mt-8 sm:border-x-0 sm:border-b-0 sm:bg-transparent sm:pt-6">{disciplines.map(({Icon,label})=><div key={label} className="flex min-w-0 flex-col items-center gap-2 text-center text-[10px] font-semibold text-[#30465a] sm:flex-row sm:justify-center sm:text-xs sm:font-bold sm:text-[#087b4b]"><Icon className="h-5 w-5 shrink-0 text-[#087b4b]"/>{label}</div>)}</div></section>
  <section className="mt-7 rounded-2xl border border-[#dfe7e3] bg-white p-6 sm:mt-8 sm:p-8"><h2 className="text-xl font-bold">El proyecto</h2><span className="mt-4 block h-0.5 w-9 bg-[#168c50]"/><p className="mt-5 max-w-none text-sm leading-6 text-[#405369]">Avizor es un proyecto en constante evolución. Combinamos datos climáticos, inteligencia artificial y reglas agronómicas validadas por especialistas para generar señales accionables que te ayuden a decidir mejor.</p><div className="mt-7 grid md:grid-cols-3"> <ProjectMetric Icon={CalendarDays} value="2026" label="Año de inicio"/><ProjectMetric Icon={MapPin} value="+150" label="Localidades cubiertas"/><ProjectMetric Icon={Leaf} value="1" label="Cultivo principal: soja"/></div></section>
  <ScopeDisclaimer/>
</main>}

function ProjectMetric({Icon,value,label}:{Icon:typeof Database;value:string;label:string}){return <div className="grid grid-cols-[52px_1fr] items-center gap-4 border-b border-[#e3eae6] py-6 last:border-0 md:block md:border-b-0 md:px-5 md:text-center"><Icon className="h-10 w-10 text-[#087b4b] md:mx-auto"/><div><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-xs uppercase leading-5 tracking-wide text-[#526477]">{label}</p></div></div>}
